### PR TITLE
Add lava check to onBlockPhysicsEvent

### PR DESCRIPTION
**Pull request by Maxopoly**
Adressing https://github.com/Civcraft/Humbug/issues/54

@Erocs That's what you meant, right?

### CODE REVIEW

**Comment by rourke750** [comment]
@erocs Will let you handle this, @Maxopoly I believe this is right.

**Comment by erocs** [comment]
LGTM

**Comment by ttk2** [comment]
so this is ready to be merged?

**Comment by Maxopoly** [comment]
Yes

**Comment by erocs** [comment]
Merged. We'll need to remember to pull a build when Jenkins is fixed.

**Pull request merged**
