### PR TITLE
Fix issue #11 

### PR DESCRIPTION
**Pull request by jjj5311**
This will not allow duplication of items they pick up and/or spawn with (armor, swords, shovels)

This will only duplicate items they drop when they die

### CODE REVIEW

**Comment by ttk2** [comment]
how are you determining this?

**Comment by jjj5311** [comment]
basically dont duplicate any equipment they have

**Comment by ttk2** [comment]
that's the only rule? what if you hand them a stack of gold nuggets (the
can and do drop gold nuggets)

**Comment by jjj5311** [comment]
they are holding it so it wont duplicate

**Comment by ttk2** [comment]
how does that logic work?

**Comment by jjj5311** [comment]
if the mob is holding the item or wearing it it doesnt get duplicated

**Comment by ttk2** [comment]
they can pick up items

**Comment by jjj5311** [comment]
yes, but they can only hold 1 thing, they dont have an inventory

**Comment by ttk2** [comment]
what if it stacks? I guess we could figure that out in testing

**Comment by jjj5311** [comment]
by 1 thing i mean 1 itemstack

**Comment by ttk2** [comment]
so hand them a stack of gold nuggets, they are now holding a stack of gold
nuggets that gets duped

**Comment by jjj5311** [comment]
No because they are still holding it. The drops like nuggets and rotten
flesh are all not held by the mob

**Comment by ttk2** [comment]
I think I understand how this works, anyone want to review it and merge?

**Comment by WildWeazel** [comment]
I'm looking at it.
@ttk2 The logic behind it is that mobs don't have inventory slots like players do, they can only have armor and weapon slots, and that's the only place that items can go that they pick up - armor to armor, everything else to weapon. If a mob has nothing equipped when it spawns it'll pick up the first stack that it comes across and that will fill the weapon slot. Then it can't pick up anything else because its single slot is full (except for combining partial stacks). So when it dies we know that the only drop that could possibly have been picked up is what it's wearing and holding, if anything. Anything else comes from the mob itself and is safe to duplicate.

**Comment by WildWeazel** [comment]
looks good, to Civtest with you

**Comment by ttk2** [comment]
just merged the other fix on top of that, will be on Civtest in a second

**Pull request merged**
