### PR TITLE
Fix for boats

### PR DESCRIPTION
**Pull request by BlackXnt**
I tested it. Boats still wont work if they don't have water underneath them.

### CODE REVIEW

**Comment by ttk2** [comment]
Why is this a problem? Use minecarts instead.

**Comment by BlackXnt** [comment]
this is a bug, it wasn't like this on 1.7. People made tunnels for boats of 1 deep high and they cant use them now. It is also annoying that the boat break a few blocks before you get to land.

**Comment by jjj5311** [comment]
We used to use toughboats for this right? i am guessing that is not updated
to 1.8?

**Comment by BlackXnt** [comment]
I will try explaining the purpose of this pull a bit better: All I did was a small modification to the way we block people from using boats on ground without water. It looks like in 1.8 the location of the boat is the same location of the block it is on. While in 1.7 the location of the boat was one block above the location of the block it was on. This change causes boats to break if there is only 1 block of water below them. I didn't change how minecraft vanilla works, our fix for boats on Humbug is the cause of this bug.

**Comment by ttk2** [comment]
oh, the auto boat breaking stuff?

**Comment by BlackXnt** [comment]
> oh, the auto boat breaking stuff?

Yes

**Pull request merged**
