### PR TITLE
1.8 banners

### PR DESCRIPTION
**Pull request by BlackXnt**
After testing on my local server and searching online I think I know what the problem is. The PlayerInteractEvent doesn't fire if the action is left or right click on air if ignoreCancelled is set
to true. So I just moved the event to the onPlayerInteractAll method.

### CODE REVIEW

**Comment by rourke750** [comment]
ok to test

**Comment by ttk2** [comment]
is this fix for the crash or somthing else? because that seems to be my 1.8.4 update on Civtest.

**Comment by BlackXnt** [comment]
> is this fix for the crash or somthing else? because that seems to be my 1.8.4 update on Civtest.

No this is a fix for something else.

**Comment by ttk2** [comment]
ok then, it passes the test, so merging.

**Comment by ttk2** [comment]
on civtest.

**Pull request merged**
