### PR TITLE
Prot nerfed against arrows to enable for 2 class PVP

### PR DESCRIPTION
**Pull request by Xavter**
A rough draft  based on what I said in https://github.com/Civcraft/Humbug/issues/16 to make prot vulnerable to arrows while keeping proj prot very effective at stopping arrows, thus making a two kit PVP system.

Some problems with first commit: the damage modifier is based on diamond armor vs iron or leather armor, where it may be doing too much extra damage. Additionally, the current prot enchantment will also be more vulnerable to thrown potions - this is easy to fix I believe but I coded this on my phone and simply couldn't get to it.

### CODE REVIEW

**Comment by rourke750** [comment]
@ttk2 What do you want to do with this?

**Comment by ttk2** [comment]
not sure.

**Comment by drjawa** [comment]
I think Xavter is looking into merging this into bergypvp rather than
humbug.

**Comment by Xavter** [comment]
Yeah, I've been drained for time, but I plan on bringing the code over to the bergecraft repository soon. You should maybe switch the issue to the BC repository, too.

**Comment by rourke750** [comment]
bump

**Comment by Xavter** [comment]
I shoulda spent this sunday coding more instead of on the server, haha. My weeks are getting more open, I will get to this as soon as possible, and there are some bits of code that are ambiguous as to whether they fit within a plugin for scarcity or PVP, so I may ask a few questions.

**Comment by ttk2** [comment]
Ask away

**Comment by Xavter** [comment]
Should the deathlog, deathred, and other pieces of 'death' code go into Bergey? I think we want mob loot multipliers and XP disabling code in Humbug, but I could see it in Bergey too: Where do these go? And where do vehicle and hunger tweaking code go?

**Comment by Xavter** [comment]
Also should we clear out existing BergeyPVP code?

**Comment by ttk2** [comment]
combat stuff only is Bergy.

**Comment by Maxopoly** [comment]
Closing this, because Xavter is most likely not gonna do dev stuff anymore or fix this pull and we wont bother with PvP balance on 1.8 anyway

**Comment by ttk2** [comment]
what happened to him anyways?

**Comment by Maxopoly** [comment]
I'm not sure either. His git account here is not his main account, he just made it for civ and rarely checks it. Also he kind of wanted to quit completly but then didnt, I really dont know.

**Pull request closed without merging**
