### PR TITLE
Disable changing spawners with eggs

### PR DESCRIPTION
**Pull request by BlackXnt**
True by default

### CODE REVIEW

**Comment by ttk2** [comment]
Yup. This is what we need. Thanks for handling it Black. Roruke will check
it over and merge when he gets a chance.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
@BlackXnt Thank you so much.

**Comment by rourke750** [comment]
ok to test

**Comment by ttk2** [comment]
update humbug on Civtest then?

**Comment by rourke750** [comment]
Yea

**Pull request merged**
