### PR TITLE
Fix Issue #17

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ttk2** [comment]
Cool thanks. Will leave for review then merge.

**Comment by jjj5311** [comment]
not needed as discussed in #17

**Comment by rourke750** [comment]
Would it still be needed just in the case of books anyways?  Since this is here anyways

**Comment by ttk2** [comment]
so should I merge this?

**Comment by drjawa** [comment]
It wouldn't hurt.

**Comment by ttk2** [comment]
this can't be merged.

**Comment by WildWeazel** [comment]
why not? looks correct

**Comment by ttk2** [comment]
no clue, github has an error.

**Comment by WildWeazel** [comment]
Oh, I see it now. Must be because they deleted their account.

**Comment by WildWeazel** [comment]
a791d0246d96cf6280a18bed07f3eabca7dfbf1f

**Comment by ttk2** [comment]
cool you can merge it.

**Comment by WildWeazel** [comment]
http://civcraft.co:8080/job/Humbug-master/32/ contains this and the fixed #34 since that build failed

**Pull request closed without merging**
