### PR TITLE
Fix combat tag on login

### PR DESCRIPTION
**Pull request by jjj5311**
Combat tag on login was using playername and expects a Player now

### CODE REVIEW

**Comment by rourke750** [comment]
Doesn't really matter as it takes either https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/CombatInterface.java#L8

Check on the 1.8.7 test server if you get tagged on login.  You should be getting tagged now at least.

**Comment by jjj5311** [comment]
my bad

**Comment by rourke750** [comment]
No problem.

**Comment by ttk2** [comment]
what about the NPC pearling issue?

**Comment by rourke750** [comment]
That needs to be tested to see if its fixed on the 1.8.7 server

**Comment by ttk2** [comment]
you made changes to fix it?

**Comment by rourke750** [comment]
yea.

**Pull request closed without merging**
