### PR TITLE
Remove bow buff

### PR DESCRIPTION
**Pull request by Maxopoly**

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
I hate you civcraftbot

**Comment by ProgrammerDan** [comment]
why remove it vs. just setting the value in config to 0?

**Comment by Maxopoly** [comment]
I mostly wanted a test build from this. It's no longer needed though because it was meant to revert a change many minecraft versions ago and by now doesnt really achieve what it's supposed to do.

**Comment by ProgrammerDan** [comment]
It looks like it would still work pretty well?

**Pull request closed without merging**
