### PR TITLE
remove disable_xp_orbs

### PR DESCRIPTION
**Pull request by jjj5311**
May add into its own method but I dont think performance wise it will even help

### CODE REVIEW

**Comment by ttk2** [comment]
we are removing this because its not duplicate with Factorymod right?

**Comment by jjj5311** [comment]
Removing cause it's essentially useless

**Comment by rourke750** [comment]
@jjj5311 useless how?  Is this code somewhere else?

**Comment by jjj5311** [comment]
Not yet, it only disabled xp orbs dropped from killing mobs... I will add a
method in the future that will actually disable all xp orbs from mobs,
mining, and whatever else you can get orbs from in vanilla

**Comment by rourke750** [comment]
Well, id rather not remove this and let people get xp without a fix :/

**Comment by jjj5311** [comment]
xp is still disabled... this only removes the orbs

**Comment by jjj5311** [comment]
https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1712

**Comment by jjj5311** [comment]
@rourke750 this should be merged

**Comment by rourke750** [comment]
Did you test to see if they would not spawn?

**Comment by jjj5311** [comment]
They xp orbs will spawn without this, however players are not awarded xp from orbs since https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1712

**Comment by rourke750** [comment]
I don't think you are linking to the right line.

**Comment by jjj5311** [comment]
yeah forgot to check the link i just copied it 

https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1768

**Comment by rourke750** [comment]
That's only triggered when a player throws an xp bottle.

**Comment by jjj5311** [comment]
Look down to the next method

**Comment by jjj5311** [comment]
https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1782

**Pull request closed without merging**
