### PR TITLE
Removing the recipes for cracked stone brick and moss cobblestone

### PR DESCRIPTION
**Pull request by BlackXnt**

### CODE REVIEW

**Comment by ttk2** [comment]
I think we have a setup in Factorymod for this already, I would prefer to
use that.

**Comment by rourke750** [comment]
ok to test

**Comment by WildWeazel** [comment]
This broke the build. Missing } and wrong annotation. @CivcraftBot you had ONE JOB

**Comment by rourke750** [comment]
This was before i fixed it lol.

**Pull request merged**
