### PR TITLE
Chunk ID fix as described in fix to cache issue for AFKPGC

### PR DESCRIPTION
**Pull request by ProgrammerDan**
See https://github.com/Civcraft/AFK-Player-GC/issues/14

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
@ttk2 since nothing's broken to date, this might not be urgent, but basically the "caching" use to scan and score results in Humbug has been horribly broken for, well, forever. I never thought to double check the logic and only realized something was wrong b/c of the work on AFKPGC and reviewing the logs, demonstrating it is broken.

**Comment by gipsy-king** [comment]
This *might* be related to some rare chunk issues I observed while working
on RB.

**Comment by ProgrammerDan** [comment]
Definitely anywhere this might have been duplicated, we should find and fix.

**Comment by ttk2** [comment]
so its just a missing set of () resulting in bad ordering of the operations?

**Comment by ProgrammerDan** [comment]
Yes, exactly. One of those nefarious bugs that can go undetected for months or years. I'm glad we found it.

**Comment by ttk2** [comment]
so is this ready to merge?

**Comment by ProgrammerDan** [comment]
Yeah should be, doesn't appear to be any objection to it so g2g.

**Comment by ttk2** [comment]
on civtest.

**Comment by ttk2** [comment]
staging for Civcraft

**Pull request merged**
