### PR TITLE
1.8 Banners

### PR DESCRIPTION
**Pull request by BlackXnt**
Allow players to equip a banner by left clicking while holding it.

### CODE REVIEW

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
Have you tested this?

**Comment by BlackXnt** [comment]
Before making the pull request I made a new plugin with the method of the event in it and it worked. I installed the new build of humbug with the pull request on my server but when I try to run the command "humbug equipping_banners true" it says "unknown option". It should be false by default. I can use some help to fix it.

**Comment by BlackXnt** [comment]
Can you build it again?

**Comment by BlackXnt** [comment]
So after my debug messages didnt show up I decided to decompile the jar the bot built for me. The changes I made weren't there. So it looks like the bot isnt doing his job properly or I am a complete idiot.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
I think what happened was it was building against the mast branch.

**Comment by rourke750** [comment]
Huh looks like it does infact build and make sure it works but does not input the code.  You should be fine with this.

**Comment by BlackXnt** [comment]
What do you mean by "not input the code"? The last 2 builds(8 and 10) still don't have any of the changes I made.

**Comment by rourke750** [comment]
Because I don't think it is meant to actually compile the pull request.  It is meant to check and make sure the pull request won't fail when merged into the main branch.  Like if you were to make it so this pull request wouldn't compile properly this would not pick it up.

**Comment by BlackXnt** [comment]
I see. Do you want to build it manually so I can test if the feature is actually working before you merge it?

**Comment by rourke750** [comment]
It looks correct.  I'm doing a feature hold until we actually go onto 1.8.3.  After that I'll flag this ready for civtest hop on quickly make sure it works and it should be good to go.

**Comment by BlackXnt** [comment]
Ok great

**Comment by ttk2** [comment]
this can't be automerged, could you rebase and resubmit

**Comment by rourke750** [comment]
I can fix it

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/Humbug/pull/42

**Pull request closed without merging**
